blueprint:
  name: Contrôle de Chauffage Avancé
  description: >
    Cette automatisation gère un thermostat intelligent en fonction de la présence, des horaires, et/ou de la détection de mouvement.
    Elle peut s'adapter à de nombreux cas d'utilisation en activant ou non les options.

    - Fonctionne avec la présence de personnes
    - Fonctionne avec des horaires de chauffage
    - Fonctionne avec des capteurs de présence
    - Plusieurs modes disponibles (vacances, fête, invité)
    - Possibilité de correction de température

    Consultez la documentation complète ici : https://community.home-assistant.io/t/advanced-heating-control/469873

  domain: automation
  input:
    climate_entity:
      name: Entité de thermostat
      selector:
        entity:
          domain: climate

    temp_comfort:
      name: Température de confort
      default: 21
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

    temp_eco:
      name: Température éco
      default: 17
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

    persons:
      name: Personnes
      description: Définir les personnes à surveiller pour la présence.
      default: []
      selector:
        entity:
          domain: person
          multiple: true

    presence_entities:
      name: Capteurs de présence
      description: Capteurs à utiliser pour la détection de mouvement ou de présence.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    schedule:
      name: Horaire principal
      description: Planification de base de l’utilisation du chauffage.
      selector:
        entity:
          domain: schedule

    schedule_holiday:
      name: Horaire des vacances
      description: Planning alternatif pour les vacances.
      default: []
      selector:
        entity:
          domain: schedule
          multiple: true

    holiday_mode:
      name: Mode vacances
      description: Activer ce commutateur pour activer le planning de vacances.
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    guest_mode:
      name: Mode invité
      description: Activer ce commutateur simulera une personne à la maison.
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    party_mode:
      name: Mode fête
      description: Forcer le chauffage en mode confort peu importe les conditions.
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    presence_only_after:
      name: Activer la détection de présence uniquement après (HH:MM)
      default: '00:00'
      selector:
        time:

    presence_only_before:
      name: Activer la détection de présence uniquement avant (HH:MM)
      default: '23:59'
      selector:
        time:

    temp_sensor:
      name: Capteur de température externe (optionnel)
      description: Si défini, ce capteur sera utilisé pour corriger la température du thermostat.
      default: []
      selector:
        entity:
          domain: sensor

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input climate_entity
  - platform: time_pattern
    minutes: "/5"
  - platform: state
    entity_id: !input persons
  - platform: state
    entity_id: !input presence_entities
  - platform: state
    entity_id: !input schedule
  - platform: state
    entity_id: !input schedule_holiday
  - platform: state
    entity_id: !input guest_mode
  - platform: state
    entity_id: !input party_mode
  - platform: state
    entity_id: !input holiday_mode
  - platform: state
    entity_id: !input temp_sensor

condition: []

action:
  - service: script.advanced_heating_control_logic
    data:
      climate_entity: !input climate_entity
      temp_comfort: !input temp_comfort
      temp_eco: !input temp_eco
      persons: !input persons
      presence_entities: !input presence_entities
      schedule: !input schedule
      schedule_holiday: !input schedule_holiday
      holiday_mode: !input holiday_mode
      guest_mode: !input guest_mode
      party_mode: !input party_mode
      presence_only_after: !input presence_only_after
      presence_only_before: !input presence_only_before
      temp_sensor: !input temp_sensor
